name: Deploy to GitHub Pages

on:
  push:
    branches:
      - integration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies (frontend)
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy to GitHub Pages
      run: |
        # This assumes you are using the `gh-pages` package for deployment.
        npm install -g gh-pages
        gh-pages -d frontend/build -b master

